name: eda
channels:
  - conda-forge
dependencies:
  - ipython=7.21.0
  - jupyter=1.0.0
  - jinja2<3.1.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.10.31
      - protobuf<=3.20.1
